//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_201_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> JobPositionId { get; set; }
        public Nullable<int> JobCategoryId { get; set; }
        public Nullable<int> RankCategoryId { get; set; }
        public Nullable<int> EmpTypeId { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string NickName { get; set; }
        public string ExtensionName { get; set; }
        public string Address { get; set; }
        public string ProvAddress { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Region { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodType { get; set; }
        public string Religion { get; set; }
        public string Citizenship { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> ShiftNo { get; set; }
        public string JoiningDate { get; set; }
        public string SeparationDate { get; set; }
        public string ReasonOfSeparation { get; set; }
        public string CasualExpiryDate { get; set; }
        public string ProbationExpiryDate { get; set; }
        public string RegularizationDate { get; set; }
        public string SSSNo { get; set; }
        public string PagibigNo { get; set; }
        public string TINNo { get; set; }
        public string BankAcctNo { get; set; }
        public string PhilHealthNo { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> TaxTypeId { get; set; }
        public Nullable<int> PayrollTypeId { get; set; }
        public Nullable<bool> SSSElig { get; set; }
        public Nullable<bool> PagibigElig { get; set; }
        public Nullable<bool> TaxElig { get; set; }
        public Nullable<bool> MediElig { get; set; }
        public Nullable<decimal> PayRestday { get; set; }
        public Nullable<int> DaysPerYear { get; set; }
        public Nullable<bool> DeductAllowance { get; set; }
        public Nullable<decimal> SLDays { get; set; }
        public Nullable<decimal> VLDays { get; set; }
        public Nullable<decimal> SILDays { get; set; }
        public Nullable<decimal> PaternityDays { get; set; }
        public string RelativeContactNo { get; set; }
        public string RelativeAddress { get; set; }
        public string DriverseLicence { get; set; }
        public string PrimarySchool { get; set; }
        public string PrimaryPeriod { get; set; }
        public string SecondarySchool { get; set; }
        public string SecondaryPeriod { get; set; }
        public string TertiarySchool { get; set; }
        public string TertiaryPeriod { get; set; }
        public string TertiaryCourse { get; set; }
        public string VocationalSchool { get; set; }
        public string VocationaSchool1 { get; set; }
        public string VocationalCourse { get; set; }
        public string PostGraduateSchool { get; set; }
        public string PostGraduatePeriod { get; set; }
        public string PostGraduateCourse { get; set; }
        public string GovExamNature { get; set; }
        public string GovExamDate { get; set; }
        public string GovExamRating { get; set; }
        public string GovExamLicense { get; set; }
        public string Father { get; set; }
        public string FatherBirthDate { get; set; }
        public string FatherContactNo { get; set; }
        public string FatherEducAttainment { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherCompany { get; set; }
        public string Mother { get; set; }
        public string MotherBirthDate { get; set; }
        public string MotherContactNo { get; set; }
        public string MotherEducAttainment { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherCompany { get; set; }
        public string Spouse { get; set; }
        public string SpouseBirthDate { get; set; }
        public string SpouseContactNo { get; set; }
        public string SpouseEducAttainment { get; set; }
        public string SpouseOccupation { get; set; }
        public string SpouseCompany { get; set; }
        public string DateTransferToStaff { get; set; }
        public string DateOfTransfer { get; set; }
        public string ContractStart { get; set; }
        public string ContractEnd { get; set; }
        public string SalaryRemarks { get; set; }
        public string MedicalStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> EmploymentStatusId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserTrailTrack { get; set; }
        public string UserLogStamp { get; set; }
    
        public virtual Position JobPosition { get; set; }
    }
}
