//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_201_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Superuser = new HashSet<Superuser>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Superuser> Superuser { get; set; }
    }
}
