//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_201_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string ADID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserTrailTrack { get; set; }
        public string UserLogStamp { get; set; }
    }
}
