//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_201_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileExtension
    {
        public int id { get; set; }
        public string File_Type { get; set; }
        public string File_Extns { get; set; }
        public bool isAccepted { get; set; }
    }
}
