//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_201_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Superuser
    {
        public int id { get; set; }
        public Nullable<int> user_type_id { get; set; }
        public string user_ADID { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
